// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: client_gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_client_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{0}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                         // gateway 版本
	KeyName       string                 `protobuf:"bytes,2,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`          // 這把 API Key 的名稱（確認打到正確的 key）
	ServerTime    string                 `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_client_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PingResp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResp) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *PingResp) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_client_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatToolSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SchemaJson    string                 `protobuf:"bytes,3,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatToolSpec) Reset() {
	*x = ChatToolSpec{}
	mi := &file_client_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatToolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatToolSpec) ProtoMessage() {}

func (x *ChatToolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatToolSpec.ProtoReflect.Descriptor instead.
func (*ChatToolSpec) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ChatToolSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatToolSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ChatToolSpec) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type ChatToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatToolCall) Reset() {
	*x = ChatToolCall{}
	mi := &file_client_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatToolCall) ProtoMessage() {}

func (x *ChatToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatToolCall.ProtoReflect.Descriptor instead.
func (*ChatToolCall) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ChatToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatToolCall) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

type ChatToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,4,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatToolResult) Reset() {
	*x = ChatToolResult{}
	mi := &file_client_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatToolResult) ProtoMessage() {}

func (x *ChatToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatToolResult.ProtoReflect.Descriptor instead.
func (*ChatToolResult) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ChatToolResult) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ChatToolResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatToolResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_client_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ChatReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Messages       []*ChatMessage         `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	ClientTools    []*ChatToolSpec        `protobuf:"bytes,4,rep,name=client_tools,json=clientTools,proto3" json:"client_tools,omitempty"`
	ContinuationId string                 `protobuf:"bytes,5,opt,name=continuation_id,json=continuationId,proto3" json:"continuation_id,omitempty"`
	ToolResults    []*ChatToolResult      `protobuf:"bytes,6,rep,name=tool_results,json=toolResults,proto3" json:"tool_results,omitempty"`
	Temperature    float32                `protobuf:"fixed32,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_client_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ChatReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ChatReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatReq) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatReq) GetClientTools() []*ChatToolSpec {
	if x != nil {
		return x.ClientTools
	}
	return nil
}

func (x *ChatReq) GetContinuationId() string {
	if x != nil {
		return x.ContinuationId
	}
	return ""
}

func (x *ChatReq) GetToolResults() []*ChatToolResult {
	if x != nil {
		return x.ToolResults
	}
	return nil
}

func (x *ChatReq) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type ChatResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "final" | "tool_calls"
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ContinuationId string                 `protobuf:"bytes,4,opt,name=continuation_id,json=continuationId,proto3" json:"continuation_id,omitempty"`
	ToolCalls      []*ChatToolCall        `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Usage          *TokenUsage            `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatResp) Reset() {
	*x = ChatResp{}
	mi := &file_client_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResp) ProtoMessage() {}

func (x *ChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResp.ProtoReflect.Descriptor instead.
func (*ChatResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ChatResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ChatResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResp) GetContinuationId() string {
	if x != nil {
		return x.ContinuationId
	}
	return ""
}

func (x *ChatResp) GetToolCalls() []*ChatToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatResp) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ChatStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStatusReq) Reset() {
	*x = ChatStatusReq{}
	mi := &file_client_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStatusReq) ProtoMessage() {}

func (x *ChatStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStatusReq.ProtoReflect.Descriptor instead.
func (*ChatStatusReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ChatStatusReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChatStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`    // 目前階段標籤（例 "Agent 2 · ToolLoop"）；active=false 時為空
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"` // 該 session 是否正在 server 端處理中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStatusResp) Reset() {
	*x = ChatStatusResp{}
	mi := &file_client_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStatusResp) ProtoMessage() {}

func (x *ChatStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStatusResp.ProtoReflect.Descriptor instead.
func (*ChatStatusResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *ChatStatusResp) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ChatStatusResp) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ChatImageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Image         []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"` // 原始圖片 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatImageReq) Reset() {
	*x = ChatImageReq{}
	mi := &file_client_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatImageReq) ProtoMessage() {}

func (x *ChatImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatImageReq.ProtoReflect.Descriptor instead.
func (*ChatImageReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *ChatImageReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ChatImageReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ChatImageReq) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type ChatImageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // 視覺模型抽出的文字（OCR / 描述）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatImageResp) Reset() {
	*x = ChatImageResp{}
	mi := &file_client_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatImageResp) ProtoMessage() {}

func (x *ChatImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatImageResp.ProtoReflect.Descriptor instead.
func (*ChatImageResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *ChatImageResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PersonaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                   // SKILL.md ## Model 段的 role
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                 // SKILL.md ## Model 段的明確 model tag
	RoleMd        string                 `protobuf:"bytes,5,opt,name=role_md,json=roleMd,proto3" json:"role_md,omitempty"` // 目前 ROLE.md 內容（衍生檔）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonaInfo) Reset() {
	*x = PersonaInfo{}
	mi := &file_client_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonaInfo) ProtoMessage() {}

func (x *PersonaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonaInfo.ProtoReflect.Descriptor instead.
func (*PersonaInfo) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *PersonaInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PersonaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonaInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PersonaInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PersonaInfo) GetRoleMd() string {
	if x != nil {
		return x.RoleMd
	}
	return ""
}

type ListPersonasReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonasReq) Reset() {
	*x = ListPersonasReq{}
	mi := &file_client_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonasReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasReq) ProtoMessage() {}

func (x *ListPersonasReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasReq.ProtoReflect.Descriptor instead.
func (*ListPersonasReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{14}
}

type ListPersonasResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personas      []*PersonaInfo         `protobuf:"bytes,1,rep,name=personas,proto3" json:"personas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonasResp) Reset() {
	*x = ListPersonasResp{}
	mi := &file_client_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonasResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasResp) ProtoMessage() {}

func (x *ListPersonasResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasResp.ProtoReflect.Descriptor instead.
func (*ListPersonasResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *ListPersonasResp) GetPersonas() []*PersonaInfo {
	if x != nil {
		return x.Personas
	}
	return nil
}

type SetPersonaModelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPersonaModelReq) Reset() {
	*x = SetPersonaModelReq{}
	mi := &file_client_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPersonaModelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPersonaModelReq) ProtoMessage() {}

func (x *SetPersonaModelReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPersonaModelReq.ProtoReflect.Descriptor instead.
func (*SetPersonaModelReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *SetPersonaModelReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SetPersonaModelReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SetPersonaModelReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UploadMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMeta) Reset() {
	*x = UploadMeta{}
	mi := &file_client_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMeta) ProtoMessage() {}

func (x *UploadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMeta.ProtoReflect.Descriptor instead.
func (*UploadMeta) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *UploadMeta) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UploadMeta) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *UploadMeta            `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"` // 只在第一則訊息帶
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // 建議 ≤64KB/則
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_client_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *UploadChunk) GetMeta() *UploadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UploadChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAck) Reset() {
	*x = UploadAck{}
	mi := &file_client_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAck) ProtoMessage() {}

func (x *UploadAck) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAck.ProtoReflect.Descriptor instead.
func (*UploadAck) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *UploadAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UploadAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type IngestJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestJobReq) Reset() {
	*x = IngestJobReq{}
	mi := &file_client_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestJobReq) ProtoMessage() {}

func (x *IngestJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestJobReq.ProtoReflect.Descriptor instead.
func (*IngestJobReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *IngestJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type IngestJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	DoneChunks    int32                  `protobuf:"varint,4,opt,name=done_chunks,json=doneChunks,proto3" json:"done_chunks,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestJobResp) Reset() {
	*x = IngestJobResp{}
	mi := &file_client_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestJobResp) ProtoMessage() {}

func (x *IngestJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestJobResp.ProtoReflect.Descriptor instead.
func (*IngestJobResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *IngestJobResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestJobResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestJobResp) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *IngestJobResp) GetDoneChunks() int32 {
	if x != nil {
		return x.DoneChunks
	}
	return 0
}

func (x *IngestJobResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GraphEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SourceFile    string                 `protobuf:"bytes,4,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	Degree        int32                  `protobuf:"varint,6,opt,name=degree,proto3" json:"degree,omitempty"` // 全圖關係數（節點大小/關鍵節點判斷用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEntity) Reset() {
	*x = GraphEntity{}
	mi := &file_client_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEntity) ProtoMessage() {}

func (x *GraphEntity) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEntity.ProtoReflect.Descriptor instead.
func (*GraphEntity) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *GraphEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphEntity) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GraphEntity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GraphEntity) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *GraphEntity) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GraphEntity) GetDegree() int32 {
	if x != nil {
		return x.Degree
	}
	return 0
}

type GraphRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRelation) Reset() {
	*x = GraphRelation{}
	mi := &file_client_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRelation) ProtoMessage() {}

func (x *GraphRelation) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRelation.ProtoReflect.Descriptor instead.
func (*GraphRelation) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *GraphRelation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GraphRelation) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GraphRelation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GraphSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphSearchReq) Reset() {
	*x = GraphSearchReq{}
	mi := &file_client_gateway_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphSearchReq) ProtoMessage() {}

func (x *GraphSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphSearchReq.ProtoReflect.Descriptor instead.
func (*GraphSearchReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{24}
}

func (x *GraphSearchReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GraphSearchReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GraphSearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*GraphEntity         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphSearchResp) Reset() {
	*x = GraphSearchResp{}
	mi := &file_client_gateway_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphSearchResp) ProtoMessage() {}

func (x *GraphSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphSearchResp.ProtoReflect.Descriptor instead.
func (*GraphSearchResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{25}
}

func (x *GraphSearchResp) GetEntities() []*GraphEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GraphContextReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityName    string                 `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Hops          int32                  `protobuf:"varint,2,opt,name=hops,proto3" json:"hops,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphContextReq) Reset() {
	*x = GraphContextReq{}
	mi := &file_client_gateway_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphContextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphContextReq) ProtoMessage() {}

func (x *GraphContextReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphContextReq.ProtoReflect.Descriptor instead.
func (*GraphContextReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{26}
}

func (x *GraphContextReq) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *GraphContextReq) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *GraphContextReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GraphContextResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *GraphEntity           `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Neighbors     []*GraphEntity         `protobuf:"bytes,2,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	Relations     []*GraphRelation       `protobuf:"bytes,3,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphContextResp) Reset() {
	*x = GraphContextResp{}
	mi := &file_client_gateway_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphContextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphContextResp) ProtoMessage() {}

func (x *GraphContextResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphContextResp.ProtoReflect.Descriptor instead.
func (*GraphContextResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{27}
}

func (x *GraphContextResp) GetCenter() *GraphEntity {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *GraphContextResp) GetNeighbors() []*GraphEntity {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *GraphContextResp) GetRelations() []*GraphRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type GraphHybridSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Hops          int32                  `protobuf:"varint,3,opt,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphHybridSearchReq) Reset() {
	*x = GraphHybridSearchReq{}
	mi := &file_client_gateway_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphHybridSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphHybridSearchReq) ProtoMessage() {}

func (x *GraphHybridSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphHybridSearchReq.ProtoReflect.Descriptor instead.
func (*GraphHybridSearchReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{28}
}

func (x *GraphHybridSearchReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GraphHybridSearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *GraphHybridSearchReq) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

type GraphHybridSearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seeds         []*GraphEntity         `protobuf:"bytes,1,rep,name=seeds,proto3" json:"seeds,omitempty"`
	Context       []*GraphContextResp    `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphHybridSearchResp) Reset() {
	*x = GraphHybridSearchResp{}
	mi := &file_client_gateway_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphHybridSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphHybridSearchResp) ProtoMessage() {}

func (x *GraphHybridSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphHybridSearchResp.ProtoReflect.Descriptor instead.
func (*GraphHybridSearchResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{29}
}

func (x *GraphHybridSearchResp) GetSeeds() []*GraphEntity {
	if x != nil {
		return x.Seeds
	}
	return nil
}

func (x *GraphHybridSearchResp) GetContext() []*GraphContextResp {
	if x != nil {
		return x.Context
	}
	return nil
}

type GraphProposedRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceEntity  string                 `protobuf:"bytes,2,opt,name=source_entity,json=sourceEntity,proto3" json:"source_entity,omitempty"`
	TargetEntity  string                 `protobuf:"bytes,3,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"`
	RelationType  string                 `protobuf:"bytes,4,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SourceFile    string                 `protobuf:"bytes,6,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	ExtractedBy   string                 `protobuf:"bytes,7,opt,name=extracted_by,json=extractedBy,proto3" json:"extracted_by,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphProposedRelation) Reset() {
	*x = GraphProposedRelation{}
	mi := &file_client_gateway_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphProposedRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphProposedRelation) ProtoMessage() {}

func (x *GraphProposedRelation) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphProposedRelation.ProtoReflect.Descriptor instead.
func (*GraphProposedRelation) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{30}
}

func (x *GraphProposedRelation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphProposedRelation) GetSourceEntity() string {
	if x != nil {
		return x.SourceEntity
	}
	return ""
}

func (x *GraphProposedRelation) GetTargetEntity() string {
	if x != nil {
		return x.TargetEntity
	}
	return ""
}

func (x *GraphProposedRelation) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *GraphProposedRelation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GraphProposedRelation) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *GraphProposedRelation) GetExtractedBy() string {
	if x != nil {
		return x.ExtractedBy
	}
	return ""
}

func (x *GraphProposedRelation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GraphProposedRelation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GraphListProposedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 空 = pending
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphListProposedReq) Reset() {
	*x = GraphListProposedReq{}
	mi := &file_client_gateway_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphListProposedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphListProposedReq) ProtoMessage() {}

func (x *GraphListProposedReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphListProposedReq.ProtoReflect.Descriptor instead.
func (*GraphListProposedReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{31}
}

func (x *GraphListProposedReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GraphListProposedReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GraphListProposedResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Relations     []*GraphProposedRelation `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphListProposedResp) Reset() {
	*x = GraphListProposedResp{}
	mi := &file_client_gateway_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphListProposedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphListProposedResp) ProtoMessage() {}

func (x *GraphListProposedResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphListProposedResp.ProtoReflect.Descriptor instead.
func (*GraphListProposedResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{32}
}

func (x *GraphListProposedResp) GetRelations() []*GraphProposedRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type GraphReviewProposedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphReviewProposedReq) Reset() {
	*x = GraphReviewProposedReq{}
	mi := &file_client_gateway_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphReviewProposedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphReviewProposedReq) ProtoMessage() {}

func (x *GraphReviewProposedReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphReviewProposedReq.ProtoReflect.Descriptor instead.
func (*GraphReviewProposedReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{33}
}

func (x *GraphReviewProposedReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VaultManifestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultManifestReq) Reset() {
	*x = VaultManifestReq{}
	mi := &file_client_gateway_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultManifestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultManifestReq) ProtoMessage() {}

func (x *VaultManifestReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultManifestReq.ProtoReflect.Descriptor instead.
func (*VaultManifestReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{34}
}

type VaultFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // vault 相對路徑（forward slash）
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ModifiedUnix  int64                  `protobuf:"varint,4,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultFileInfo) Reset() {
	*x = VaultFileInfo{}
	mi := &file_client_gateway_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultFileInfo) ProtoMessage() {}

func (x *VaultFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultFileInfo.ProtoReflect.Descriptor instead.
func (*VaultFileInfo) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{35}
}

func (x *VaultFileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VaultFileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VaultFileInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *VaultFileInfo) GetModifiedUnix() int64 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

type VaultManifestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*VaultFileInfo       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultManifestResp) Reset() {
	*x = VaultManifestResp{}
	mi := &file_client_gateway_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultManifestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultManifestResp) ProtoMessage() {}

func (x *VaultManifestResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultManifestResp.ProtoReflect.Descriptor instead.
func (*VaultManifestResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{36}
}

func (x *VaultManifestResp) GetFiles() []*VaultFileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type VaultFetchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultFetchReq) Reset() {
	*x = VaultFetchReq{}
	mi := &file_client_gateway_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultFetchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultFetchReq) ProtoMessage() {}

func (x *VaultFetchReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultFetchReq.ProtoReflect.Descriptor instead.
func (*VaultFetchReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{37}
}

func (x *VaultFetchReq) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type VaultFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultFileChunk) Reset() {
	*x = VaultFileChunk{}
	mi := &file_client_gateway_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultFileChunk) ProtoMessage() {}

func (x *VaultFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultFileChunk.ProtoReflect.Descriptor instead.
func (*VaultFileChunk) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{38}
}

func (x *VaultFileChunk) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VaultFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VaultFileChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type VerifySearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySearchReq) Reset() {
	*x = VerifySearchReq{}
	mi := &file_client_gateway_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySearchReq) ProtoMessage() {}

func (x *VerifySearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySearchReq.ProtoReflect.Descriptor instead.
func (*VerifySearchReq) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{39}
}

func (x *VerifySearchReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *VerifySearchReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *VerifySearchReq) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type VerifySearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySearchResp) Reset() {
	*x = VerifySearchResp{}
	mi := &file_client_gateway_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySearchResp) ProtoMessage() {}

func (x *VerifySearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_client_gateway_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySearchResp.ProtoReflect.Descriptor instead.
func (*VerifySearchResp) Descriptor() ([]byte, []int) {
	return file_client_gateway_proto_rawDescGZIP(), []int{40}
}

func (x *VerifySearchResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_client_gateway_proto protoreflect.FileDescriptor

const file_client_gateway_proto_rawDesc = "" +
	"\n" +
	"\x14client_gateway.proto\x12\x10agent_gateway.v1\"\t\n" +
	"\aPingReq\"`\n" +
	"\bPingResp\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\bkey_name\x18\x02 \x01(\tR\akeyName\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\tR\n" +
	"serverTime\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"e\n" +
	"\fChatToolSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vschema_json\x18\x03 \x01(\tR\n" +
	"schemaJson\"O\n" +
	"\fChatToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\tR\bargsJson\"{\n" +
	"\x0eChatToolResult\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x04 \x01(\bR\aisError\"\x81\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\xd1\x02\n" +
	"\aChatReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x129\n" +
	"\bmessages\x18\x03 \x03(\v2\x1d.agent_gateway.v1.ChatMessageR\bmessages\x12A\n" +
	"\fclient_tools\x18\x04 \x03(\v2\x1e.agent_gateway.v1.ChatToolSpecR\vclientTools\x12'\n" +
	"\x0fcontinuation_id\x18\x05 \x01(\tR\x0econtinuationId\x12C\n" +
	"\ftool_results\x18\x06 \x03(\v2 .agent_gateway.v1.ChatToolResultR\vtoolResults\x12 \n" +
	"\vtemperature\x18\a \x01(\x02R\vtemperature\"\xf7\x01\n" +
	"\bChatResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12'\n" +
	"\x0fcontinuation_id\x18\x04 \x01(\tR\x0econtinuationId\x12=\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x1e.agent_gateway.v1.ChatToolCallR\ttoolCalls\x122\n" +
	"\x05usage\x18\x06 \x01(\v2\x1c.agent_gateway.v1.TokenUsageR\x05usage\".\n" +
	"\rChatStatusReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\">\n" +
	"\x0eChatStatusResp\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\"[\n" +
	"\fChatImageReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\"#\n" +
	"\rChatImageResp\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x7f\n" +
	"\vPersonaInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x17\n" +
	"\arole_md\x18\x05 \x01(\tR\x06roleMd\"\x11\n" +
	"\x0fListPersonasReq\"M\n" +
	"\x10ListPersonasResp\x129\n" +
	"\bpersonas\x18\x01 \x03(\v2\x1d.agent_gateway.v1.PersonaInfoR\bpersonas\"Y\n" +
	"\x12SetPersonaModelReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\";\n" +
	"\n" +
	"UploadMeta\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"p\n" +
	"\vUploadChunk\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agent_gateway.v1.UploadMetaR\x04meta\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\":\n" +
	"\tUploadAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"%\n" +
	"\fIngestJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x91\x01\n" +
	"\rIngestJobResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x12\x1f\n" +
	"\vdone_chunks\x18\x04 \x01(\x05R\n" +
	"doneChunks\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xae\x01\n" +
	"\vGraphEntity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsource_file\x18\x04 \x01(\tR\n" +
	"sourceFile\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x16\n" +
	"\x06degree\x18\x06 \x01(\x05R\x06degree\"S\n" +
	"\rGraphRelation\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"<\n" +
	"\x0eGraphSearchReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"L\n" +
	"\x0fGraphSearchResp\x129\n" +
	"\bentities\x18\x01 \x03(\v2\x1d.agent_gateway.v1.GraphEntityR\bentities\"\\\n" +
	"\x0fGraphContextReq\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x12\x12\n" +
	"\x04hops\x18\x02 \x01(\x05R\x04hops\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xc5\x01\n" +
	"\x10GraphContextResp\x125\n" +
	"\x06center\x18\x01 \x01(\v2\x1d.agent_gateway.v1.GraphEntityR\x06center\x12;\n" +
	"\tneighbors\x18\x02 \x03(\v2\x1d.agent_gateway.v1.GraphEntityR\tneighbors\x12=\n" +
	"\trelations\x18\x03 \x03(\v2\x1f.agent_gateway.v1.GraphRelationR\trelations\"U\n" +
	"\x14GraphHybridSearchReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12\x12\n" +
	"\x04hops\x18\x03 \x01(\x05R\x04hops\"\x8a\x01\n" +
	"\x15GraphHybridSearchResp\x123\n" +
	"\x05seeds\x18\x01 \x03(\v2\x1d.agent_gateway.v1.GraphEntityR\x05seeds\x12<\n" +
	"\acontext\x18\x02 \x03(\v2\".agent_gateway.v1.GraphContextRespR\acontext\"\xb1\x02\n" +
	"\x15GraphProposedRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rsource_entity\x18\x02 \x01(\tR\fsourceEntity\x12#\n" +
	"\rtarget_entity\x18\x03 \x01(\tR\ftargetEntity\x12#\n" +
	"\rrelation_type\x18\x04 \x01(\tR\frelationType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vsource_file\x18\x06 \x01(\tR\n" +
	"sourceFile\x12!\n" +
	"\fextracted_by\x18\a \x01(\tR\vextractedBy\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"D\n" +
	"\x14GraphListProposedReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"^\n" +
	"\x15GraphListProposedResp\x12E\n" +
	"\trelations\x18\x01 \x03(\v2'.agent_gateway.v1.GraphProposedRelationR\trelations\"(\n" +
	"\x16GraphReviewProposedReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x12\n" +
	"\x10VaultManifestReq\"t\n" +
	"\rVaultFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12#\n" +
	"\rmodified_unix\x18\x04 \x01(\x03R\fmodifiedUnix\"J\n" +
	"\x11VaultManifestResp\x125\n" +
	"\x05files\x18\x01 \x03(\v2\x1f.agent_gateway.v1.VaultFileInfoR\x05files\"%\n" +
	"\rVaultFetchReq\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"J\n" +
	"\x0eVaultFileChunk\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"W\n" +
	"\x0fVerifySearchReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"(\n" +
	"\x10VerifySearchResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total2\xca\v\n" +
	"\rClientGateway\x12=\n" +
	"\x04Ping\x12\x19.agent_gateway.v1.PingReq\x1a\x1a.agent_gateway.v1.PingResp\x12=\n" +
	"\x04Chat\x12\x19.agent_gateway.v1.ChatReq\x1a\x1a.agent_gateway.v1.ChatResp\x12O\n" +
	"\n" +
	"ChatStatus\x12\x1f.agent_gateway.v1.ChatStatusReq\x1a .agent_gateway.v1.ChatStatusResp\x12L\n" +
	"\tChatImage\x12\x1e.agent_gateway.v1.ChatImageReq\x1a\x1f.agent_gateway.v1.ChatImageResp\x12U\n" +
	"\fListPersonas\x12!.agent_gateway.v1.ListPersonasReq\x1a\".agent_gateway.v1.ListPersonasResp\x12V\n" +
	"\x0fSetPersonaModel\x12$.agent_gateway.v1.SetPersonaModelReq\x1a\x1d.agent_gateway.v1.PersonaInfo\x12L\n" +
	"\fUploadIngest\x12\x1d.agent_gateway.v1.UploadChunk\x1a\x1b.agent_gateway.v1.UploadAck(\x01\x12O\n" +
	"\fGetIngestJob\x12\x1e.agent_gateway.v1.IngestJobReq\x1a\x1f.agent_gateway.v1.IngestJobResp\x12R\n" +
	"\vGraphSearch\x12 .agent_gateway.v1.GraphSearchReq\x1a!.agent_gateway.v1.GraphSearchResp\x12U\n" +
	"\fGraphContext\x12!.agent_gateway.v1.GraphContextReq\x1a\".agent_gateway.v1.GraphContextResp\x12d\n" +
	"\x11GraphHybridSearch\x12&.agent_gateway.v1.GraphHybridSearchReq\x1a'.agent_gateway.v1.GraphHybridSearchResp\x12d\n" +
	"\x11GraphListProposed\x12&.agent_gateway.v1.GraphListProposedReq\x1a'.agent_gateway.v1.GraphListProposedResp\x12i\n" +
	"\x14GraphApproveProposed\x12(.agent_gateway.v1.GraphReviewProposedReq\x1a'.agent_gateway.v1.GraphProposedRelation\x12h\n" +
	"\x13GraphRejectProposed\x12(.agent_gateway.v1.GraphReviewProposedReq\x1a'.agent_gateway.v1.GraphProposedRelation\x12X\n" +
	"\rVaultManifest\x12\".agent_gateway.v1.VaultManifestReq\x1a#.agent_gateway.v1.VaultManifestResp\x12Q\n" +
	"\n" +
	"VaultFetch\x12\x1f.agent_gateway.v1.VaultFetchReq\x1a .agent_gateway.v1.VaultFileChunk0\x01\x12U\n" +
	"\fVerifySearch\x12!.agent_gateway.v1.VerifySearchReq\x1a\".agent_gateway.v1.VerifySearchRespB%Z#agent_gatway/pb/gatewaypb;gatewaypbb\x06proto3"

var (
	file_client_gateway_proto_rawDescOnce sync.Once
	file_client_gateway_proto_rawDescData []byte
)

func file_client_gateway_proto_rawDescGZIP() []byte {
	file_client_gateway_proto_rawDescOnce.Do(func() {
		file_client_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_gateway_proto_rawDesc), len(file_client_gateway_proto_rawDesc)))
	})
	return file_client_gateway_proto_rawDescData
}

var file_client_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_client_gateway_proto_goTypes = []any{
	(*PingReq)(nil),                // 0: agent_gateway.v1.PingReq
	(*PingResp)(nil),               // 1: agent_gateway.v1.PingResp
	(*ChatMessage)(nil),            // 2: agent_gateway.v1.ChatMessage
	(*ChatToolSpec)(nil),           // 3: agent_gateway.v1.ChatToolSpec
	(*ChatToolCall)(nil),           // 4: agent_gateway.v1.ChatToolCall
	(*ChatToolResult)(nil),         // 5: agent_gateway.v1.ChatToolResult
	(*TokenUsage)(nil),             // 6: agent_gateway.v1.TokenUsage
	(*ChatReq)(nil),                // 7: agent_gateway.v1.ChatReq
	(*ChatResp)(nil),               // 8: agent_gateway.v1.ChatResp
	(*ChatStatusReq)(nil),          // 9: agent_gateway.v1.ChatStatusReq
	(*ChatStatusResp)(nil),         // 10: agent_gateway.v1.ChatStatusResp
	(*ChatImageReq)(nil),           // 11: agent_gateway.v1.ChatImageReq
	(*ChatImageResp)(nil),          // 12: agent_gateway.v1.ChatImageResp
	(*PersonaInfo)(nil),            // 13: agent_gateway.v1.PersonaInfo
	(*ListPersonasReq)(nil),        // 14: agent_gateway.v1.ListPersonasReq
	(*ListPersonasResp)(nil),       // 15: agent_gateway.v1.ListPersonasResp
	(*SetPersonaModelReq)(nil),     // 16: agent_gateway.v1.SetPersonaModelReq
	(*UploadMeta)(nil),             // 17: agent_gateway.v1.UploadMeta
	(*UploadChunk)(nil),            // 18: agent_gateway.v1.UploadChunk
	(*UploadAck)(nil),              // 19: agent_gateway.v1.UploadAck
	(*IngestJobReq)(nil),           // 20: agent_gateway.v1.IngestJobReq
	(*IngestJobResp)(nil),          // 21: agent_gateway.v1.IngestJobResp
	(*GraphEntity)(nil),            // 22: agent_gateway.v1.GraphEntity
	(*GraphRelation)(nil),          // 23: agent_gateway.v1.GraphRelation
	(*GraphSearchReq)(nil),         // 24: agent_gateway.v1.GraphSearchReq
	(*GraphSearchResp)(nil),        // 25: agent_gateway.v1.GraphSearchResp
	(*GraphContextReq)(nil),        // 26: agent_gateway.v1.GraphContextReq
	(*GraphContextResp)(nil),       // 27: agent_gateway.v1.GraphContextResp
	(*GraphHybridSearchReq)(nil),   // 28: agent_gateway.v1.GraphHybridSearchReq
	(*GraphHybridSearchResp)(nil),  // 29: agent_gateway.v1.GraphHybridSearchResp
	(*GraphProposedRelation)(nil),  // 30: agent_gateway.v1.GraphProposedRelation
	(*GraphListProposedReq)(nil),   // 31: agent_gateway.v1.GraphListProposedReq
	(*GraphListProposedResp)(nil),  // 32: agent_gateway.v1.GraphListProposedResp
	(*GraphReviewProposedReq)(nil), // 33: agent_gateway.v1.GraphReviewProposedReq
	(*VaultManifestReq)(nil),       // 34: agent_gateway.v1.VaultManifestReq
	(*VaultFileInfo)(nil),          // 35: agent_gateway.v1.VaultFileInfo
	(*VaultManifestResp)(nil),      // 36: agent_gateway.v1.VaultManifestResp
	(*VaultFetchReq)(nil),          // 37: agent_gateway.v1.VaultFetchReq
	(*VaultFileChunk)(nil),         // 38: agent_gateway.v1.VaultFileChunk
	(*VerifySearchReq)(nil),        // 39: agent_gateway.v1.VerifySearchReq
	(*VerifySearchResp)(nil),       // 40: agent_gateway.v1.VerifySearchResp
}
var file_client_gateway_proto_depIdxs = []int32{
	2,  // 0: agent_gateway.v1.ChatReq.messages:type_name -> agent_gateway.v1.ChatMessage
	3,  // 1: agent_gateway.v1.ChatReq.client_tools:type_name -> agent_gateway.v1.ChatToolSpec
	5,  // 2: agent_gateway.v1.ChatReq.tool_results:type_name -> agent_gateway.v1.ChatToolResult
	4,  // 3: agent_gateway.v1.ChatResp.tool_calls:type_name -> agent_gateway.v1.ChatToolCall
	6,  // 4: agent_gateway.v1.ChatResp.usage:type_name -> agent_gateway.v1.TokenUsage
	13, // 5: agent_gateway.v1.ListPersonasResp.personas:type_name -> agent_gateway.v1.PersonaInfo
	17, // 6: agent_gateway.v1.UploadChunk.meta:type_name -> agent_gateway.v1.UploadMeta
	22, // 7: agent_gateway.v1.GraphSearchResp.entities:type_name -> agent_gateway.v1.GraphEntity
	22, // 8: agent_gateway.v1.GraphContextResp.center:type_name -> agent_gateway.v1.GraphEntity
	22, // 9: agent_gateway.v1.GraphContextResp.neighbors:type_name -> agent_gateway.v1.GraphEntity
	23, // 10: agent_gateway.v1.GraphContextResp.relations:type_name -> agent_gateway.v1.GraphRelation
	22, // 11: agent_gateway.v1.GraphHybridSearchResp.seeds:type_name -> agent_gateway.v1.GraphEntity
	27, // 12: agent_gateway.v1.GraphHybridSearchResp.context:type_name -> agent_gateway.v1.GraphContextResp
	30, // 13: agent_gateway.v1.GraphListProposedResp.relations:type_name -> agent_gateway.v1.GraphProposedRelation
	35, // 14: agent_gateway.v1.VaultManifestResp.files:type_name -> agent_gateway.v1.VaultFileInfo
	0,  // 15: agent_gateway.v1.ClientGateway.Ping:input_type -> agent_gateway.v1.PingReq
	7,  // 16: agent_gateway.v1.ClientGateway.Chat:input_type -> agent_gateway.v1.ChatReq
	9,  // 17: agent_gateway.v1.ClientGateway.ChatStatus:input_type -> agent_gateway.v1.ChatStatusReq
	11, // 18: agent_gateway.v1.ClientGateway.ChatImage:input_type -> agent_gateway.v1.ChatImageReq
	14, // 19: agent_gateway.v1.ClientGateway.ListPersonas:input_type -> agent_gateway.v1.ListPersonasReq
	16, // 20: agent_gateway.v1.ClientGateway.SetPersonaModel:input_type -> agent_gateway.v1.SetPersonaModelReq
	18, // 21: agent_gateway.v1.ClientGateway.UploadIngest:input_type -> agent_gateway.v1.UploadChunk
	20, // 22: agent_gateway.v1.ClientGateway.GetIngestJob:input_type -> agent_gateway.v1.IngestJobReq
	24, // 23: agent_gateway.v1.ClientGateway.GraphSearch:input_type -> agent_gateway.v1.GraphSearchReq
	26, // 24: agent_gateway.v1.ClientGateway.GraphContext:input_type -> agent_gateway.v1.GraphContextReq
	28, // 25: agent_gateway.v1.ClientGateway.GraphHybridSearch:input_type -> agent_gateway.v1.GraphHybridSearchReq
	31, // 26: agent_gateway.v1.ClientGateway.GraphListProposed:input_type -> agent_gateway.v1.GraphListProposedReq
	33, // 27: agent_gateway.v1.ClientGateway.GraphApproveProposed:input_type -> agent_gateway.v1.GraphReviewProposedReq
	33, // 28: agent_gateway.v1.ClientGateway.GraphRejectProposed:input_type -> agent_gateway.v1.GraphReviewProposedReq
	34, // 29: agent_gateway.v1.ClientGateway.VaultManifest:input_type -> agent_gateway.v1.VaultManifestReq
	37, // 30: agent_gateway.v1.ClientGateway.VaultFetch:input_type -> agent_gateway.v1.VaultFetchReq
	39, // 31: agent_gateway.v1.ClientGateway.VerifySearch:input_type -> agent_gateway.v1.VerifySearchReq
	1,  // 32: agent_gateway.v1.ClientGateway.Ping:output_type -> agent_gateway.v1.PingResp
	8,  // 33: agent_gateway.v1.ClientGateway.Chat:output_type -> agent_gateway.v1.ChatResp
	10, // 34: agent_gateway.v1.ClientGateway.ChatStatus:output_type -> agent_gateway.v1.ChatStatusResp
	12, // 35: agent_gateway.v1.ClientGateway.ChatImage:output_type -> agent_gateway.v1.ChatImageResp
	15, // 36: agent_gateway.v1.ClientGateway.ListPersonas:output_type -> agent_gateway.v1.ListPersonasResp
	13, // 37: agent_gateway.v1.ClientGateway.SetPersonaModel:output_type -> agent_gateway.v1.PersonaInfo
	19, // 38: agent_gateway.v1.ClientGateway.UploadIngest:output_type -> agent_gateway.v1.UploadAck
	21, // 39: agent_gateway.v1.ClientGateway.GetIngestJob:output_type -> agent_gateway.v1.IngestJobResp
	25, // 40: agent_gateway.v1.ClientGateway.GraphSearch:output_type -> agent_gateway.v1.GraphSearchResp
	27, // 41: agent_gateway.v1.ClientGateway.GraphContext:output_type -> agent_gateway.v1.GraphContextResp
	29, // 42: agent_gateway.v1.ClientGateway.GraphHybridSearch:output_type -> agent_gateway.v1.GraphHybridSearchResp
	32, // 43: agent_gateway.v1.ClientGateway.GraphListProposed:output_type -> agent_gateway.v1.GraphListProposedResp
	30, // 44: agent_gateway.v1.ClientGateway.GraphApproveProposed:output_type -> agent_gateway.v1.GraphProposedRelation
	30, // 45: agent_gateway.v1.ClientGateway.GraphRejectProposed:output_type -> agent_gateway.v1.GraphProposedRelation
	36, // 46: agent_gateway.v1.ClientGateway.VaultManifest:output_type -> agent_gateway.v1.VaultManifestResp
	38, // 47: agent_gateway.v1.ClientGateway.VaultFetch:output_type -> agent_gateway.v1.VaultFileChunk
	40, // 48: agent_gateway.v1.ClientGateway.VerifySearch:output_type -> agent_gateway.v1.VerifySearchResp
	32, // [32:49] is the sub-list for method output_type
	15, // [15:32] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_client_gateway_proto_init() }
func file_client_gateway_proto_init() {
	if File_client_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_gateway_proto_rawDesc), len(file_client_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_gateway_proto_goTypes,
		DependencyIndexes: file_client_gateway_proto_depIdxs,
		MessageInfos:      file_client_gateway_proto_msgTypes,
	}.Build()
	File_client_gateway_proto = out.File
	file_client_gateway_proto_goTypes = nil
	file_client_gateway_proto_depIdxs = nil
}
