// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: client_gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientGateway_Ping_FullMethodName                 = "/agent_gateway.v1.ClientGateway/Ping"
	ClientGateway_Chat_FullMethodName                 = "/agent_gateway.v1.ClientGateway/Chat"
	ClientGateway_ChatStatus_FullMethodName           = "/agent_gateway.v1.ClientGateway/ChatStatus"
	ClientGateway_ChatImage_FullMethodName            = "/agent_gateway.v1.ClientGateway/ChatImage"
	ClientGateway_ListPersonas_FullMethodName         = "/agent_gateway.v1.ClientGateway/ListPersonas"
	ClientGateway_SetPersonaModel_FullMethodName      = "/agent_gateway.v1.ClientGateway/SetPersonaModel"
	ClientGateway_UploadIngest_FullMethodName         = "/agent_gateway.v1.ClientGateway/UploadIngest"
	ClientGateway_GetIngestJob_FullMethodName         = "/agent_gateway.v1.ClientGateway/GetIngestJob"
	ClientGateway_GraphSearch_FullMethodName          = "/agent_gateway.v1.ClientGateway/GraphSearch"
	ClientGateway_GraphContext_FullMethodName         = "/agent_gateway.v1.ClientGateway/GraphContext"
	ClientGateway_GraphHybridSearch_FullMethodName    = "/agent_gateway.v1.ClientGateway/GraphHybridSearch"
	ClientGateway_GraphListProposed_FullMethodName    = "/agent_gateway.v1.ClientGateway/GraphListProposed"
	ClientGateway_GraphApproveProposed_FullMethodName = "/agent_gateway.v1.ClientGateway/GraphApproveProposed"
	ClientGateway_GraphRejectProposed_FullMethodName  = "/agent_gateway.v1.ClientGateway/GraphRejectProposed"
	ClientGateway_VerifySearch_FullMethodName         = "/agent_gateway.v1.ClientGateway/VerifySearch"
)

// ClientGatewayClient is the client API for ClientGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientGateway — dev_pub_0.9 外網部署的唯一 client-facing 介面。
// pub_client（外網桌面 client）的全部後端流量（對話/上傳/圖譜/審核/Verify）都收斂到這裡，
// gateway 再以內部 mTLS 轉發給 agents / agent_graph / agent_embedding。
//
// 認證：所有 RPC 都要在 gRPC metadata 帶 `x-api-key` + `x-device-id`；
// gateway 驗 key（SHA-256 比對 api_keys 表）並做「一 Key 一裝置」TOFU 綁定。
type ClientGatewayClient interface {
	// Ping 供 Test Connection 用，同時驗 API Key 有效性。
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	// Chat 同步對話（轉發 agents AgentService.Chat；client tools / continuation 全保留）。
	Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
	// ChatStatus 回報某 session 目前處理到哪個 Agent 階段（client 每秒輪詢，顯示在秒數前）。
	// gateway 內部 HTTP 打 agents /api/chat/status/:session_id。
	ChatStatus(ctx context.Context, in *ChatStatusReq, opts ...grpc.CallOption) (*ChatStatusResp, error)
	// ChatImage 對話附加圖片辨識：視覺模型抽文字（供當下對話辨識）+ 同時 ingest 進 RAG。
	// gateway 內部 HTTP 打 agents /api/chat/image；回傳抽出的文字，client 併進該輪訊息。
	ChatImage(ctx context.Context, in *ChatImageReq, opts ...grpc.CallOption) (*ChatImageResp, error)
	// Persona 模型設定（轉發 agents /api/personas；client「Models」分頁設定 Agent 1-4 的 model）。
	ListPersonas(ctx context.Context, in *ListPersonasReq, opts ...grpc.CallOption) (*ListPersonasResp, error)
	SetPersonaModel(ctx context.Context, in *SetPersonaModelReq, opts ...grpc.CallOption) (*PersonaInfo, error)
	// UploadIngest 文件攝取上傳（client-streaming；轉發 agents AgentService.UploadIngest）。
	UploadIngest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, UploadAck], error)
	GetIngestJob(ctx context.Context, in *IngestJobReq, opts ...grpc.CallOption) (*IngestJobResp, error)
	// Graph*（轉發 agent_graph GraphService）
	GraphSearch(ctx context.Context, in *GraphSearchReq, opts ...grpc.CallOption) (*GraphSearchResp, error)
	GraphContext(ctx context.Context, in *GraphContextReq, opts ...grpc.CallOption) (*GraphContextResp, error)
	GraphHybridSearch(ctx context.Context, in *GraphHybridSearchReq, opts ...grpc.CallOption) (*GraphHybridSearchResp, error)
	GraphListProposed(ctx context.Context, in *GraphListProposedReq, opts ...grpc.CallOption) (*GraphListProposedResp, error)
	GraphApproveProposed(ctx context.Context, in *GraphReviewProposedReq, opts ...grpc.CallOption) (*GraphProposedRelation, error)
	GraphRejectProposed(ctx context.Context, in *GraphReviewProposedReq, opts ...grpc.CallOption) (*GraphProposedRelation, error)
	// VerifySearch 上傳後檢索驗證（gateway 內部 HTTPS 打 agent_embedding /api/search）。
	VerifySearch(ctx context.Context, in *VerifySearchReq, opts ...grpc.CallOption) (*VerifySearchResp, error)
}

type clientGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewClientGatewayClient(cc grpc.ClientConnInterface) ClientGatewayClient {
	return &clientGatewayClient{cc}
}

func (c *clientGatewayClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, ClientGateway_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResp)
	err := c.cc.Invoke(ctx, ClientGateway_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) ChatStatus(ctx context.Context, in *ChatStatusReq, opts ...grpc.CallOption) (*ChatStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatStatusResp)
	err := c.cc.Invoke(ctx, ClientGateway_ChatStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) ChatImage(ctx context.Context, in *ChatImageReq, opts ...grpc.CallOption) (*ChatImageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatImageResp)
	err := c.cc.Invoke(ctx, ClientGateway_ChatImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) ListPersonas(ctx context.Context, in *ListPersonasReq, opts ...grpc.CallOption) (*ListPersonasResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPersonasResp)
	err := c.cc.Invoke(ctx, ClientGateway_ListPersonas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) SetPersonaModel(ctx context.Context, in *SetPersonaModelReq, opts ...grpc.CallOption) (*PersonaInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersonaInfo)
	err := c.cc.Invoke(ctx, ClientGateway_SetPersonaModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) UploadIngest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, UploadAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientGateway_ServiceDesc.Streams[0], ClientGateway_UploadIngest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, UploadAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientGateway_UploadIngestClient = grpc.ClientStreamingClient[UploadChunk, UploadAck]

func (c *clientGatewayClient) GetIngestJob(ctx context.Context, in *IngestJobReq, opts ...grpc.CallOption) (*IngestJobResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestJobResp)
	err := c.cc.Invoke(ctx, ClientGateway_GetIngestJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) GraphSearch(ctx context.Context, in *GraphSearchReq, opts ...grpc.CallOption) (*GraphSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphSearchResp)
	err := c.cc.Invoke(ctx, ClientGateway_GraphSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) GraphContext(ctx context.Context, in *GraphContextReq, opts ...grpc.CallOption) (*GraphContextResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphContextResp)
	err := c.cc.Invoke(ctx, ClientGateway_GraphContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) GraphHybridSearch(ctx context.Context, in *GraphHybridSearchReq, opts ...grpc.CallOption) (*GraphHybridSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphHybridSearchResp)
	err := c.cc.Invoke(ctx, ClientGateway_GraphHybridSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) GraphListProposed(ctx context.Context, in *GraphListProposedReq, opts ...grpc.CallOption) (*GraphListProposedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphListProposedResp)
	err := c.cc.Invoke(ctx, ClientGateway_GraphListProposed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) GraphApproveProposed(ctx context.Context, in *GraphReviewProposedReq, opts ...grpc.CallOption) (*GraphProposedRelation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphProposedRelation)
	err := c.cc.Invoke(ctx, ClientGateway_GraphApproveProposed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) GraphRejectProposed(ctx context.Context, in *GraphReviewProposedReq, opts ...grpc.CallOption) (*GraphProposedRelation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphProposedRelation)
	err := c.cc.Invoke(ctx, ClientGateway_GraphRejectProposed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientGatewayClient) VerifySearch(ctx context.Context, in *VerifySearchReq, opts ...grpc.CallOption) (*VerifySearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySearchResp)
	err := c.cc.Invoke(ctx, ClientGateway_VerifySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientGatewayServer is the server API for ClientGateway service.
// All implementations must embed UnimplementedClientGatewayServer
// for forward compatibility.
//
// ClientGateway — dev_pub_0.9 外網部署的唯一 client-facing 介面。
// pub_client（外網桌面 client）的全部後端流量（對話/上傳/圖譜/審核/Verify）都收斂到這裡，
// gateway 再以內部 mTLS 轉發給 agents / agent_graph / agent_embedding。
//
// 認證：所有 RPC 都要在 gRPC metadata 帶 `x-api-key` + `x-device-id`；
// gateway 驗 key（SHA-256 比對 api_keys 表）並做「一 Key 一裝置」TOFU 綁定。
type ClientGatewayServer interface {
	// Ping 供 Test Connection 用，同時驗 API Key 有效性。
	Ping(context.Context, *PingReq) (*PingResp, error)
	// Chat 同步對話（轉發 agents AgentService.Chat；client tools / continuation 全保留）。
	Chat(context.Context, *ChatReq) (*ChatResp, error)
	// ChatStatus 回報某 session 目前處理到哪個 Agent 階段（client 每秒輪詢，顯示在秒數前）。
	// gateway 內部 HTTP 打 agents /api/chat/status/:session_id。
	ChatStatus(context.Context, *ChatStatusReq) (*ChatStatusResp, error)
	// ChatImage 對話附加圖片辨識：視覺模型抽文字（供當下對話辨識）+ 同時 ingest 進 RAG。
	// gateway 內部 HTTP 打 agents /api/chat/image；回傳抽出的文字，client 併進該輪訊息。
	ChatImage(context.Context, *ChatImageReq) (*ChatImageResp, error)
	// Persona 模型設定（轉發 agents /api/personas；client「Models」分頁設定 Agent 1-4 的 model）。
	ListPersonas(context.Context, *ListPersonasReq) (*ListPersonasResp, error)
	SetPersonaModel(context.Context, *SetPersonaModelReq) (*PersonaInfo, error)
	// UploadIngest 文件攝取上傳（client-streaming；轉發 agents AgentService.UploadIngest）。
	UploadIngest(grpc.ClientStreamingServer[UploadChunk, UploadAck]) error
	GetIngestJob(context.Context, *IngestJobReq) (*IngestJobResp, error)
	// Graph*（轉發 agent_graph GraphService）
	GraphSearch(context.Context, *GraphSearchReq) (*GraphSearchResp, error)
	GraphContext(context.Context, *GraphContextReq) (*GraphContextResp, error)
	GraphHybridSearch(context.Context, *GraphHybridSearchReq) (*GraphHybridSearchResp, error)
	GraphListProposed(context.Context, *GraphListProposedReq) (*GraphListProposedResp, error)
	GraphApproveProposed(context.Context, *GraphReviewProposedReq) (*GraphProposedRelation, error)
	GraphRejectProposed(context.Context, *GraphReviewProposedReq) (*GraphProposedRelation, error)
	// VerifySearch 上傳後檢索驗證（gateway 內部 HTTPS 打 agent_embedding /api/search）。
	VerifySearch(context.Context, *VerifySearchReq) (*VerifySearchResp, error)
	mustEmbedUnimplementedClientGatewayServer()
}

// UnimplementedClientGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientGatewayServer struct{}

func (UnimplementedClientGatewayServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedClientGatewayServer) Chat(context.Context, *ChatReq) (*ChatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedClientGatewayServer) ChatStatus(context.Context, *ChatStatusReq) (*ChatStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatStatus not implemented")
}
func (UnimplementedClientGatewayServer) ChatImage(context.Context, *ChatImageReq) (*ChatImageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatImage not implemented")
}
func (UnimplementedClientGatewayServer) ListPersonas(context.Context, *ListPersonasReq) (*ListPersonasResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPersonas not implemented")
}
func (UnimplementedClientGatewayServer) SetPersonaModel(context.Context, *SetPersonaModelReq) (*PersonaInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPersonaModel not implemented")
}
func (UnimplementedClientGatewayServer) UploadIngest(grpc.ClientStreamingServer[UploadChunk, UploadAck]) error {
	return status.Error(codes.Unimplemented, "method UploadIngest not implemented")
}
func (UnimplementedClientGatewayServer) GetIngestJob(context.Context, *IngestJobReq) (*IngestJobResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIngestJob not implemented")
}
func (UnimplementedClientGatewayServer) GraphSearch(context.Context, *GraphSearchReq) (*GraphSearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphSearch not implemented")
}
func (UnimplementedClientGatewayServer) GraphContext(context.Context, *GraphContextReq) (*GraphContextResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphContext not implemented")
}
func (UnimplementedClientGatewayServer) GraphHybridSearch(context.Context, *GraphHybridSearchReq) (*GraphHybridSearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphHybridSearch not implemented")
}
func (UnimplementedClientGatewayServer) GraphListProposed(context.Context, *GraphListProposedReq) (*GraphListProposedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphListProposed not implemented")
}
func (UnimplementedClientGatewayServer) GraphApproveProposed(context.Context, *GraphReviewProposedReq) (*GraphProposedRelation, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphApproveProposed not implemented")
}
func (UnimplementedClientGatewayServer) GraphRejectProposed(context.Context, *GraphReviewProposedReq) (*GraphProposedRelation, error) {
	return nil, status.Error(codes.Unimplemented, "method GraphRejectProposed not implemented")
}
func (UnimplementedClientGatewayServer) VerifySearch(context.Context, *VerifySearchReq) (*VerifySearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySearch not implemented")
}
func (UnimplementedClientGatewayServer) mustEmbedUnimplementedClientGatewayServer() {}
func (UnimplementedClientGatewayServer) testEmbeddedByValue()                       {}

// UnsafeClientGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientGatewayServer will
// result in compilation errors.
type UnsafeClientGatewayServer interface {
	mustEmbedUnimplementedClientGatewayServer()
}

func RegisterClientGatewayServer(s grpc.ServiceRegistrar, srv ClientGatewayServer) {
	// If the following call panics, it indicates UnimplementedClientGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientGateway_ServiceDesc, srv)
}

func _ClientGateway_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).Chat(ctx, req.(*ChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_ChatStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).ChatStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_ChatStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).ChatStatus(ctx, req.(*ChatStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_ChatImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatImageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).ChatImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_ChatImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).ChatImage(ctx, req.(*ChatImageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_ListPersonas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersonasReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).ListPersonas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_ListPersonas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).ListPersonas(ctx, req.(*ListPersonasReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_SetPersonaModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPersonaModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).SetPersonaModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_SetPersonaModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).SetPersonaModel(ctx, req.(*SetPersonaModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_UploadIngest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientGatewayServer).UploadIngest(&grpc.GenericServerStream[UploadChunk, UploadAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientGateway_UploadIngestServer = grpc.ClientStreamingServer[UploadChunk, UploadAck]

func _ClientGateway_GetIngestJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).GetIngestJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_GetIngestJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).GetIngestJob(ctx, req.(*IngestJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_GraphSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).GraphSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_GraphSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).GraphSearch(ctx, req.(*GraphSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_GraphContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphContextReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).GraphContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_GraphContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).GraphContext(ctx, req.(*GraphContextReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_GraphHybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphHybridSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).GraphHybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_GraphHybridSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).GraphHybridSearch(ctx, req.(*GraphHybridSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_GraphListProposed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphListProposedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).GraphListProposed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_GraphListProposed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).GraphListProposed(ctx, req.(*GraphListProposedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_GraphApproveProposed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphReviewProposedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).GraphApproveProposed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_GraphApproveProposed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).GraphApproveProposed(ctx, req.(*GraphReviewProposedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_GraphRejectProposed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphReviewProposedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).GraphRejectProposed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_GraphRejectProposed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).GraphRejectProposed(ctx, req.(*GraphReviewProposedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientGateway_VerifySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientGatewayServer).VerifySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientGateway_VerifySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientGatewayServer).VerifySearch(ctx, req.(*VerifySearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientGateway_ServiceDesc is the grpc.ServiceDesc for ClientGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent_gateway.v1.ClientGateway",
	HandlerType: (*ClientGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ClientGateway_Ping_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _ClientGateway_Chat_Handler,
		},
		{
			MethodName: "ChatStatus",
			Handler:    _ClientGateway_ChatStatus_Handler,
		},
		{
			MethodName: "ChatImage",
			Handler:    _ClientGateway_ChatImage_Handler,
		},
		{
			MethodName: "ListPersonas",
			Handler:    _ClientGateway_ListPersonas_Handler,
		},
		{
			MethodName: "SetPersonaModel",
			Handler:    _ClientGateway_SetPersonaModel_Handler,
		},
		{
			MethodName: "GetIngestJob",
			Handler:    _ClientGateway_GetIngestJob_Handler,
		},
		{
			MethodName: "GraphSearch",
			Handler:    _ClientGateway_GraphSearch_Handler,
		},
		{
			MethodName: "GraphContext",
			Handler:    _ClientGateway_GraphContext_Handler,
		},
		{
			MethodName: "GraphHybridSearch",
			Handler:    _ClientGateway_GraphHybridSearch_Handler,
		},
		{
			MethodName: "GraphListProposed",
			Handler:    _ClientGateway_GraphListProposed_Handler,
		},
		{
			MethodName: "GraphApproveProposed",
			Handler:    _ClientGateway_GraphApproveProposed_Handler,
		},
		{
			MethodName: "GraphRejectProposed",
			Handler:    _ClientGateway_GraphRejectProposed_Handler,
		},
		{
			MethodName: "VerifySearch",
			Handler:    _ClientGateway_VerifySearch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadIngest",
			Handler:       _ClientGateway_UploadIngest_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "client_gateway.proto",
}
