// @ai:generated by=claude-sonnet-5 date=2026-07-01
package views

import "github.com/maoxiaoyue/hypgo/pkg/schema"

// RegisterSchemas 向 Schema Registry 登錄所有桌面視圖（Protocol "desktop"）。
func RegisterSchemas() {
	schema.RegisterDesktop("view/chat", "Chat tab: synchronous chat with the agent, supports local tool round-trips", nil, nil)
	schema.RegisterDesktop("view/upload", "Upload tab: PDF / image / text ingestion, polls job status", nil, nil)
	schema.RegisterDesktop("view/tools", "Tools tab: register / edit / delete local executable tools", nil, nil)
	schema.RegisterDesktop("view/settings", "Settings tab: RAG Base URL / RAG ID / TLS", nil, nil)
}
